### ISSUE TITLE
Midi input on RG351V

### ISSUE THREAD

**Issue by Armillary** [jasonporritt/rg351_m8c#15]
It appears from using multiple usb midi devices that while aconnect is finding the midi inputs the application isn't able to map those inputs. No input is detected in the midi settings.

**Comment by scrubberfox** [comment]
I think you can only use 1 device with a single MIDI input and output, nothing to big and fancy with lots of ins and outs
I use a USB-C to USB adapter to connect a cheap 1 in 1 out midi usb cable and it works fine!

**Comment by Armillary** [comment]
I have since given this a test with a different setup and found that it was possible to use the midi input just fine. Admittedly part of that was also user error so I can close this one!
