### ISSUE TITLE
RG351V - Slow/Choppy connection

### ISSUE THREAD

**Issue by sushyoshi** [jasonporritt/rg351_m8c#18]
I have been having this problem running the m8c with ArkOs:

After setup and running the program I can access the bouncing cube screen. When I connect the Teensy, the screen loads to the Song screen of the M8 however the screen is slowly flickering, and the controls seem to be unresponsive or lag too much. It feels like the program is not able to obtain a stable connection with the teensy so it gets very laggy.
After a few program restarts and reset the teensy, the program starts lagging and then suddenly it stops flickering and works well.

I am not sure what causes this lag and why sometimes it works. I tried different usb cables and have the same issue.

I tried to change the firmware of the RG351V to AmberElec but I could not adapt your m8c build to that firmware.

Can you help out?

**Comment by eternalcult** [comment]
I bought the RG351V a few days ago and had the same problem. I've found a decision.
Short answer: You should update m8c.
But you can't just get source files from m8c repository, you must make a linux build inside RG351V.
How to do it:
1. RG351V - Options  - Enable Remote Services
2. Connect from PC to RG351V using ssh. (You have to google it)
3. Default user/password for Anbernic - ark/ark
4. Make a m8c build with instruction from m8c repository - "Linux / MacOS (building from source)"
5. Check build workability with "./m8c" in terminal with connected to headless m8
6. It should start, but control buttons and sound doesn't work now
7. So, get this build from RG351V to your computer and replace _m8c folder for new one.
8. But before that copy gamecontrollerdb.txt and insert it in new _m8c folder.
9. Try to run

**Comment by sushyoshi** [comment]
Thanks! That is a great detailed explanation.

I can confirm this works.
