### ISSUE TITLE
Compile errors

### ISSUE THREAD

**Issue by mwoodruff** [jasonporritt/rg351_m8c#2]
Doesn't look like an m8c binary is included, and I've had troubles getting it to compile. Does the serial library need compiled from source as well, or something else I may have missed?

**Comment by jasonporritt** [comment]
Download the zip file of one of the releases rather than a zip of the repository. The releases contain a compiled binary and the code from the m8c repository if you need to rebuild it.

https://github.com/jasonporritt/rg351_m8c/releases

**Comment by mwoodruff** [comment]
Thanks, Jason. I should have thought of that. I did a git clone. Out of curiosity, what did you have to do to get it to compile?

**Comment by smootalicious** [comment]
install/reinstall libserialport-dev libsdl2-dev build-essential libc6-dev linux-libc-dev - look in setup/_setup_build_tools.sh
