### ISSUE TITLE
Config gamepad ignored

### ISSUE THREAD

**Issue by apiel** [jasonporritt/rg351_m8c#7]
I am running the gamepad_config and everything goes well, but when I start the M8 client, all those config are ignored. How should I proceed to get it working?

**Comment by apiel** [comment]
So somehow it seem that we need to edit /home/ark/.local/share/m8c/config.ini
But I am still not able to get the right setting for the moment. Also, I don't manage to quit the app.

**Comment by apiel** [comment]
So this is my config.ini
```
[graphics]
fullscreen=false
use_gpu=true
idle_ms=10
wait_for_device=false
wait_packets=128
[keyboard]
key_up=82
key_left=80
key_down=81
key_right=79
key_select=225
key_select_alt=4
key_start=44
key_start_alt=22
key_opt=226
key_opt_alt=29
key_edit=224
key_edit_alt=27
key_delete=76
key_reset=21
[gamepad]
gamepad_up=11
gamepad_left=13
gamepad_down=12
gamepad_right=14
gamepad_select=1
gamepad_start=6
gamepad_opt=2
gamepad_edit=0
gamepad_quit=4
gamepad_reset=3
gamepad_analog_threshold=32766
gamepad_analog_invert=false
gamepad_analog_axis_updown=1
gamepad_analog_axis_leftright=0
gamepad_analog_axis_select=4
gamepad_analog_axis_start=5
gamepad_analog_axis_opt=-1
gamepad_analog_axis_edit=-1
```
The important part is gamepad.
Now if I press B+select it will exit the M8.
B is to select the menu
A to change the value

**Comment by smootalicious** [comment]
Looks like you figured it out! I'll see if I can make the instructions clearer for the future.
